"""initial

Revision ID: 76dbc5bf64ee
Revises: 
Create Date: 2025-12-06 19:57:53.525742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76dbc5bf64ee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_logs',
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('access_logs_pk'))
    )
    op.create_index(op.f('access_logs_id'), 'access_logs', ['id'], unique=False)
    op.create_index(op.f('access_logs_session_id'), 'access_logs', ['session_id'], unique=False)
    op.create_index(op.f('access_logs_user_id'), 'access_logs', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default='{"theme": "system", "notifications": {"reminders": true, "health_tips": true}}', nullable=False),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pk'))
    )
    op.create_index(op.f('users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('users_phone'), 'users', ['phone'], unique=True)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.Text(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(), nullable=False),
    sa.Column('device_name', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_sessions_user_id_users_fk')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_sessions_pk'))
    )
    op.create_index(op.f('user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=False)
    op.create_index(op.f('user_sessions_session_id'), 'user_sessions', ['session_id'], unique=True)
    op.create_index(op.f('user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('user_sessions_session_id'), table_name='user_sessions')
    op.drop_index(op.f('user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('users_phone'), table_name='users')
    op.drop_index(op.f('users_id'), table_name='users')
    op.drop_index(op.f('users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('access_logs_user_id'), table_name='access_logs')
    op.drop_index(op.f('access_logs_session_id'), table_name='access_logs')
    op.drop_index(op.f('access_logs_id'), table_name='access_logs')
    op.drop_table('access_logs')
    # ### end Alembic commands ###
